export const LANGUAGES = [
  { name: 'ABAP (SAP)', category: '*', loc: 50, serverKey: 'ABAP' },
  { name: 'ASP', category: '*', loc: 45, serverKey: 'ASP' },
  { name: 'Assembler', category: '*', loc: 120, serverKey: 'ASSEMBLER' },
  { name: 'Brio', category: '+', loc: 40, serverKey: 'BRIO' },
  { name: 'C', category: '*', loc: 110, serverKey: 'C' },
  { name: 'C++', category: '*', loc: 100, serverKey: 'C_PLUS_PLUS' },
  { name: 'C#', category: '*', loc: 80, serverKey: 'C_SHARP' },
  { name: 'COBOL', category: '*', loc: 90, serverKey: 'COBOL' },
  {
    name: 'Cognos Impromptu Scripts',
    category: '+',
    loc: 45,
    serverKey: 'COGNOS_IMPROMPTU_SCRIPTS',
  },
  {
    name: 'Cross System Products (CSP)',
    category: '+',
    loc: 55,
    serverKey: 'CROSS_SYSTEM_PRODUCTS_CSP',
  },
  { name: 'Cool:Gen/IEF', category: '*', loc: 70, serverKey: 'COOL_GEN_IEF' },
  { name: 'Datastage', category: '', loc: 50, serverKey: 'DATASTAGE' },
  { name: 'Excel', category: '*', loc: 30, serverKey: 'EXCEL' },
  { name: 'Focus', category: '*', loc: 60, serverKey: 'FOCUS' },
  { name: 'FoxPro', category: '', loc: 45, serverKey: 'FOXPRO' },
  { name: 'HTML', category: '*', loc: 35, serverKey: 'HTML' },
  { name: 'J2EE', category: '*', loc: 85, serverKey: 'J2EE' },
  { name: 'Java', category: '*', loc: 90, serverKey: 'JAVA' },
  { name: 'JavaScript', category: '*', loc: 70, serverKey: 'JAVASCRIPT' },
  { name: 'JCL', category: '*', loc: 60, serverKey: 'JCL' },
  { name: 'LINC II', category: '', loc: 50, serverKey: 'LINC_II' },
  { name: 'Lotus Notes', category: '*', loc: 45, serverKey: 'LOTUS_NOTES' },
  { name: 'Natural', category: '*', loc: 55, serverKey: 'NATURAL' },
  { name: '.NET', category: '*', loc: 80, serverKey: 'DOT_NET' },
  { name: 'Oracle', category: '*', loc: 65, serverKey: 'ORACLE' },
  { name: 'PACBASE', category: '*', loc: 70, serverKey: 'PACBASE' },
  { name: 'Perl', category: '*', loc: 60, serverKey: 'PERL' },
  { name: 'PL/I', category: '*', loc: 80, serverKey: 'PL_I' },
  { name: 'PL/SQL', category: '*', loc: 75, serverKey: 'PL_SQL' },
  { name: 'Powerbuilder', category: '*', loc: 65, serverKey: 'POWERBUILDER' },
  { name: 'REXX', category: '*', loc: 55, serverKey: 'REXX' },
  { name: 'Sabretalk', category: '*', loc: 50, serverKey: 'SABRETALK' },
  { name: 'SAS', category: '*', loc: 45, serverKey: 'SAS' },
  { name: 'Siebel', category: '*', loc: 60, serverKey: 'SIEBEL' },
  { name: 'SLOGAN', category: '*', loc: 55, serverKey: 'SLOGAN' },
  { name: 'SQL', category: '*', loc: 40, serverKey: 'SQL' },
  { name: 'VB.NET', category: '*', loc: 75, serverKey: 'VB_NET' },
  { name: 'Visual Basic', category: '*', loc: 70, serverKey: 'VISUAL_BASIC' },
  { name: 'Python', category: '*', loc: 65, serverKey: 'PYTHON' },
].sort((a, b) => a.name.localeCompare(b.name));
